name: STL and AMF Slicing
author: Roman Dvorak
description: Slice your models
inputs:
  configuration:
    description: 'Configuration'
    required: true
    default: 'slice.yml'
  printer:
    description: 'Printer'
    required: true
    default: 'default_printer.ini'
  src_folder:
    description: 'Folder with STL/AMF files'
    required: false
    default: 'stl'
  dst_folder:
    description: 'Output'
    required: false
    default: 'gcode'
runs:
  using: "docker"
  image: "Dockerfile"
  #args:
  #- "/home/slice.py"
    - "${{ inputs.printer }}"
  #- "--config=${{ github.workspace }}/${{ inputs.configuration }}"
  #- "--src_folder=${{ github.workspace }}/${{ inputs.src_folder }}"
  #- "--dst_folder=${{ github.workspace }}/${{ inputs.dst_folder }}"
branding:
  icon: 'layers'  
  color: 'orange'
