name: STL and AMF Slicing
author: Roman Dvorak
description: Slice your models
inputs:
  src_folder:
    description: 'Folder with STL/AMF files'
    required: false
    default: 'STL'
  dst_folder:
    description: 'Output'
    required: false
    default: 'gcode'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.src_folder }}
  - ${{ inputs.dst_folder }}
branding:
  icon: 'layers'  
  color: 'orange'
