name: STL and AMF Slicing
author: Roman Dvorak
description: Slice your models
inputs:
  folder:
    description: 'Folder with STL/AMF files'
    required: false
    default: 'STL'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - 'test'
  # pre-entrypoint: 'aaa.sh'
  entrypoint: 'slice.py'
